services:
  - type: web
    name: task-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString

databases:
  - name: task-manager-db
    databaseName: taskmanager
    user: taskmanager 